config:
  send_anonymous_usage_stats: False
  use_colors: True

chaos:
  target: raw_db_fivetran
  outputs:
    raw_db_fivetran:
      type: postgres
      host: postgres-postgresql.postgres.svc.cluster.local
      user: raw_src_usr
      password: raw_src_usr123
      port: 5432
      dbname: raw_db_fivetran
      schema: public
      threads: 12
