name: Testing YAML Linting Strategies

on:
  push:
    branches:
      - chaos

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          file_or_dir: '.'
          config_file: .yamllint.yml
          format: parsable
          strict: false
          no_warnings: true
